#!/usr/bin/env bash
# PRD-E: Keep last N generations per backup category, delete older.
# Run weekly via systemd timer.
set -e -u -o pipefail

KEEP=${THALAMUS_BACKUP_KEEP:-5}
LOG=~/.openclaw/thalamus/state/backup_cleanup.log

log() { echo "[$(date -Iseconds)] $*" | tee -a "$LOG"; }

cleanup_glob() {
  local pattern="$1"
  local label="$2"
  # newest first; skip first KEEP, delete rest
  local matches
  mapfile -t matches < <(ls -1t $pattern 2>/dev/null || true)
  if [ "${#matches[@]}" -le "$KEEP" ]; then
    log "  $label: ${#matches[@]} files (≤${KEEP}, no cleanup)"
    return 0
  fi
  local deleted=0
  for ((i=KEEP; i<${#matches[@]}; i++)); do
    local f="${matches[$i]}"
    rm -rf -- "$f"
    deleted=$((deleted+1))
  done
  log "  $label: kept ${KEEP} newest, deleted ${deleted}"
}

log "=== Backup cleanup START (KEEP=$KEEP) ==="

# 1) openclaw.json backups
cleanup_glob "$HOME/.openclaw/openclaw.json.before-*"            "openclaw.json.before-*"
cleanup_glob "$HOME/.openclaw/openclaw.json.bak.*"               "openclaw.json.bak.*"
cleanup_glob "$HOME/.openclaw/openclaw.json.clobbered.*"         "openclaw.json.clobbered.*"

# 2) thalamus vector store backups
cleanup_glob "$HOME/.openclaw/thalamus/state/vectors.bak.*"      "vectors.bak.*"

# 3) src file backups (auto-generated by humans/agents)
cleanup_glob "$HOME/projects-alcyone/openclaw-thalamus/src/*.before-*" "src/*.before-*"

log "=== Backup cleanup DONE ==="
