#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 2 ]]; then
  echo "usage: $0 <verdict_file> <pr_number> [repo_dir]" >&2
  exit 64
fi

verdict_file="$1"
pr_number="$2"
repo_dir="${3:-$PWD}"

if [[ ! -f "$verdict_file" ]]; then
  echo "verdict file not found: $verdict_file" >&2
  exit 66
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

verdict="$(grep -Eim1 '^(verdict|VERDICT|Verdict)[[:space:]:=]+' "$verdict_file" | sed -E 's/.*[=:][[:space:]]*//; s/[[:space:]]+$//' || true)"
if [[ -z "$verdict" ]]; then verdict="UNKNOWN"; fi
case "${verdict^^}" in
  APPROVE|APPROVED) verdict_label="APPROVED ✅" ;;
  REJECT|REJECTED) verdict_label="REJECTED ❌" ;;
  *) verdict_label="$verdict" ;;
esac

packet="$(grep -Eom1 'pkt_[A-Za-z0-9_:-]+' "$verdict_file" || true)"
resolver="$(grep -Eom1 'sha256:[A-Za-z0-9]+' "$verdict_file" | head -1 || true)"
if [[ -n "$resolver" ]]; then resolver="${resolver:0:23}…"; fi

{
  echo "## Inspector Audit"
  echo
  echo "**Verdict**: $verdict_label"
  echo
  echo "### Findings / Notes"
  echo
  sed -n '1,220p' "$verdict_file" | sed 's/[[:space:]]\+$//' | sed 's/^/> /'
  echo
  echo "### Thalamus packet"
  if [[ -n "$packet" || -n "$resolver" ]]; then
    echo "\`${packet:-unknown}\` resolver=\`${resolver:-unknown}\`"
  else
    echo "No packet reference found in verdict file."
  fi
  echo
  echo "---"
  echo "*Generated by Alcyone Inspector @ $(date -Iseconds)*"
} > "$tmp"

cd "$repo_dir"
gh pr comment "$pr_number" --body-file "$tmp"
echo "posted inspector verdict to PR #$pr_number"
